/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package deepl_novel_translation;

import com.dropbox.core.DbxException;
import com.dropbox.core.DbxRequestConfig;
import com.dropbox.core.v2.DbxClientV2;
import com.dropbox.core.v2.files.ListFolderResult;
import com.dropbox.core.v2.files.Metadata;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import javax.annotation.Nullable;

public class App {

    private static final String ACCESS_TOKEN = System.getenv("ACCESS_TOKEN");
    private ConcurrentLinkedQueue<String> chapters = new ConcurrentLinkedQueue<String>();
    private ConcurrentLinkedQueue<String> translated = new ConcurrentLinkedQueue<String>();
    private DbxClientV2 client;
    private final int TRANSLATION_CONSUMER_THREADS = 2;
    private final int DOWNLOAD_CONSUMER_THREADS = 10;

    @Nullable
    private ListFolderResult getDropboxListFolderResult(DbxClientV2 client, String novelName) {
        ListFolderResult result = null;
        try {
            result = client.files().listFolder("/" + novelName);
        } catch (DbxException e) {
            System.out.println(String.format("Issue pulling folder %s: %s", novelName, e.getMessage()));
        }
        return result;
    }

    public void instantiateDropboxClient() {
        // Create Dropbox client
        DbxRequestConfig config = DbxRequestConfig.newBuilder("Apps/Chinese_Light_Novels").build();
        this.client = new DbxClientV2(config, ACCESS_TOKEN);
        return;
    }

    public ArrayList<String> getNovelChapters(String novelName) {
        ListFolderResult result = this.getDropboxListFolderResult(this.client, novelName);
        ArrayList<String> chaptersList = new ArrayList<String>();
        while (result != null) {
            for (Metadata metadata : result.getEntries()) {
                String path = metadata.getPathDisplay();
                chaptersList.add(path);
            }

            if (!result.getHasMore()) {
                break;
            }
            try {
                result = this.client.files().listFolderContinue(result.getCursor());
            } catch (DbxException e) {
                break;
            }
        }
        return chaptersList;
    }

    public void executeTranslatorConsumers() {
        ExecutorService executor = Executors.newFixedThreadPool(TRANSLATION_CONSUMER_THREADS);
        LinkedList<Future<?>> tasks = new LinkedList<Future<?>>();
        for (int i = 0; i < TRANSLATION_CONSUMER_THREADS; i++) {
            Future<?> future = executor.submit(new TranslationConsumer(this.chapters, this.translated));
            tasks.add(future);
        }
        for (Future<?> future : tasks) {
            try {
                future.get();
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
            }
        }
        executor.shutdown();
    }

    public void executeDownloadConsumers(List<String> chaptersList) {
        ExecutorService executor = Executors.newFixedThreadPool(DOWNLOAD_CONSUMER_THREADS);
        LinkedList<Future<?>> tasks = new LinkedList<Future<?>>();
        ConcurrentLinkedQueue<String> chaptersQueue = new ConcurrentLinkedQueue<String>(chaptersList);
        for (int i = 0; i < DOWNLOAD_CONSUMER_THREADS; i++) {
            Future<?> future = executor.submit(new DownloadConsumer(chaptersQueue, this.chapters, this.client));
            tasks.add(future);
        }
        for (Future<?> future : tasks) {
            try {
                future.get();
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
            }
        }
        executor.shutdown();
    }

    public void writeChaptersToDirectory(String directoryPath) {

        File directory = new File(directoryPath);

        // Create the directory if it does not exist
        if (!directory.exists()) {
            directory.mkdirs();
        }

        while (!this.translated.isEmpty()) {
            String chapter = this.translated.poll();
            int titleEndPostion = chapter.indexOf("\n");
            String fileName = chapter.substring(chapter.lastIndexOf("/"), titleEndPostion);
            String translatedText = chapter.substring(titleEndPostion + 1);
            try {
                File file = new File(directory, fileName);

                FileWriter writer = new FileWriter(file);
                writer.write(translatedText);
                writer.close();
            } catch (IOException e) {
                System.out.println("An error occurred writing file: " + fileName);
                e.printStackTrace();
            }
        }
    }

    public static void main(String args[]) {
        if (args.length != 2) {
            System.out.println(
                    "Needs exactly 2 arguments to run:\n 1. The directory in dropbox which holds the novel.\n 2. ");
            return;
        }
        String novelDropBoxDirectoryPath = args[0];
        String directoryPath = args[1];
        App app = new App();
        app.instantiateDropboxClient();
        ArrayList<String> chaptersList = app.getNovelChapters(novelDropBoxDirectoryPath);
        chaptersList.sort(new Comparator<String>() {
            @Override
            public int compare(String s1, String s2) {
                String[] a = s1.split("-")[0].split("/");
                String[] b = s2.split("-")[0].split("/");
                int firstNumber1 = Integer.parseInt(a[a.length - 1]);
                int firstNumber2 = Integer.parseInt(b[b.length - 1]);
                return Integer.compare(firstNumber1, firstNumber2);
            }
        });
        app.executeDownloadConsumers(chaptersList.subList(0, 2));
        app.executeTranslatorConsumers();
        app.writeChaptersToDirectory(directoryPath);
        System.out.println("Compeleted Translations");
    }
}
